# Generated by Django 4.0.1 on 2022-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0002_rename_order_receiver_order_order_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='worker_geodezis',
            field=models.CharField(blank=True, max_length=250, verbose_name='Worker geodezis'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_ispolnitel',
            field=models.CharField(blank=True, max_length=250, verbose_name='Worker ispolnitel'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_leader',
            field=models.CharField(blank=True, max_length=250, verbose_name='Worker leader'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_ogogd',
            field=models.CharField(blank=True, max_length=250, verbose_name='Worker ogogd'),
        ),
    ]
