# Generated by Django 4.0.1 on 2022-01-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0003_alter_object_worker_geodezis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programwork',
            old_name='status_program_work',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='programwork',
            name='agreement_date',
        ),
        migrations.RemoveField(
            model_name='programwork',
            name='file',
        ),
        migrations.RemoveField(
            model_name='programwork',
            name='programworkform',
        ),
        migrations.RemoveField(
            model_name='programworkform',
            name='status',
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a0',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a1_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a1_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a1_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a7_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a7_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a7_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a8_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a9_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a9_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='a9_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Pogramma ish fayli'),
        ),
        migrations.AddField(
            model_name='programworkform',
            name='programwork',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programwork', to='topografiya.programwork'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProgramWorkFormTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a9_2_1', models.TextField(blank=True)),
                ('a9_2_2', models.TextField(blank=True)),
                ('a9_2_3', models.TextField(blank=True)),
                ('a9_2_4', models.TextField(blank=True)),
                ('a9_2_5', models.TextField(blank=True)),
                ('a9_2_6', models.TextField(blank=True)),
                ('a9_2_7', models.TextField(blank=True)),
                ('programworkform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programworkform2', to='topografiya.programworkform')),
            ],
            options={
                'verbose_name_plural': 'ProgramWorkFormTable2',
            },
        ),
        migrations.CreateModel(
            name='ProgramWorkFormTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a7_1_1', models.TextField(blank=True)),
                ('a7_1_2', models.TextField(blank=True)),
                ('a7_1_3', models.TextField(blank=True)),
                ('a7_1_4', models.TextField(blank=True)),
                ('a7_1_5', models.TextField(blank=True)),
                ('programworkform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programworkform', to='topografiya.programworkform')),
            ],
            options={
                'verbose_name_plural': 'ProgramWorkFormTable1',
            },
        ),
    ]
