# Generated by Django 4.0.1 on 2022-01-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0004_rename_status_program_work_programwork_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programworkform',
            old_name='a13',
            new_name='program_work_creator',
        ),
    ]
