# Generated by Django 4.0.1 on 2022-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0005_rename_a13_programworkform_program_work_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programwork',
            name='comment',
        ),
        migrations.AddField(
            model_name='history',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
