# Generated by Django 4.0.1 on 2022-01-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0006_remove_programwork_comment_history_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerobject',
            name='poyasnitel_file',
        ),
        migrations.RemoveField(
            model_name='workerobject',
            name='raw_measurements_data_file',
        ),
        migrations.RemoveField(
            model_name='workerobject',
            name='topografik_file',
        ),
        migrations.AddField(
            model_name='workerobject',
            name='vidimes_file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/vidimes', verbose_name='Vidimes hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='workerobject',
            name='abris_file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/abrisfiles', verbose_name='Abris hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='workerobject',
            name='jurnal_file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/jurnalfiles', verbose_name='Jurnal hujjat fayli'),
        ),
        migrations.AlterField(
            model_name='workerobject',
            name='kroki_file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/krokifiles', verbose_name='Kroki hujjat fayli'),
        ),
        migrations.CreateModel(
            name='TopografikPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('workerobject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjecttopografikplan', to='topografiya.workerobject')),
            ],
            options={
                'verbose_name_plural': 'TopografikPlan',
            },
        ),
        migrations.CreateModel(
            name='SirieFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirie_file', models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli')),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('workerobject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectsiriefiles', to='topografiya.workerobject')),
            ],
            options={
                'verbose_name_plural': 'SirieFiles',
            },
        ),
        migrations.CreateModel(
            name='PoyasitelniyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('workerobject', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectpoyasitelniy', to='topografiya.workerobject')),
            ],
            options={
                'verbose_name_plural': 'PoyasitelniyForm',
            },
        ),
    ]
