# Generated by Django 4.0.1 on 2022-02-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0007_remove_workerobject_poyasnitel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramWorkReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Qaytarilgan fayl')),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programworkreject', to='topografiya.programwork')),
            ],
            options={
                'verbose_name_plural': 'ProgramWorkReject',
            },
        ),
    ]
