# Generated by Django 4.0.1 on 2022-02-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0008_programworkreject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programworkreject',
            old_name='object',
            new_name='programowork',
        ),
    ]
