# Generated by Django 4.0.1 on 2022-02-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0010_programworkreject_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siriefiles',
            name='sirie_file',
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_1',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla1'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_10',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla10'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_11',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla11'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_2',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_3',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_4',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla4'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_5',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla5'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_6',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla6'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_7',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla7'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_8',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla8'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file1_9',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla9'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_1',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_1'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_2',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_2'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_3',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_3'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_4',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_4'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_5',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_5'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_6',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_6'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file2_7',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla2_7'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_1',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_1'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_10',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_10'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_2',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_2'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_3',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_3'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_4',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_4'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_5',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_5'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_6',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_6'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_7',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_7'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_8',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_8'),
        ),
        migrations.AddField(
            model_name='siriefiles',
            name='file3_9',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/siriefiles', verbose_name='Hujjat fayli bpla3_9'),
        ),
    ]
