# Generated by Django 4.0.1 on 2022-02-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0011_remove_siriefiles_sirie_file_siriefiles_file1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b16_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b16_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b19',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b19_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b19_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b20',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b21',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b3_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b8_1_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='b_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_17',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_18',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_19',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_20',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_21',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_22',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_23',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_24',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_25',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_26',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='c_9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poyasitelniyform',
            name='d_9',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PoyasitelniyFormTable4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b18_1', models.TextField(blank=True)),
                ('b18_2', models.TextField(blank=True)),
                ('b18_3', models.TextField(blank=True)),
                ('b18_4', models.TextField(blank=True)),
                ('b18_5', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('poyasitelniyform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectpoyasitelniyformtable4', to='topografiya.poyasitelniyform')),
            ],
            options={
                'verbose_name_plural': 'PoyasitelniyFormTable4',
            },
        ),
        migrations.CreateModel(
            name='PoyasitelniyFormTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b17_1', models.TextField(blank=True)),
                ('b17_2', models.TextField(blank=True)),
                ('b17_3', models.TextField(blank=True)),
                ('b17_4', models.TextField(blank=True)),
                ('b17_5', models.TextField(blank=True)),
                ('b17_6', models.TextField(blank=True)),
                ('b17_7', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('poyasitelniyform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectpoyasitelniyformtable3', to='topografiya.poyasitelniyform')),
            ],
            options={
                'verbose_name_plural': 'PoyasitelniyFormTable3',
            },
        ),
        migrations.CreateModel(
            name='PoyasitelniyFormTable2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b9_1', models.TextField(blank=True)),
                ('b9_2', models.TextField(blank=True)),
                ('b9_3', models.TextField(blank=True)),
                ('b9_4', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('poyasitelniyform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectpoyasitelniyformtable2', to='topografiya.poyasitelniyform')),
            ],
            options={
                'verbose_name_plural': 'PoyasitelniyFormTable2',
            },
        ),
        migrations.CreateModel(
            name='PoyasitelniyFormTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b8_1', models.TextField(blank=True)),
                ('b8_2', models.TextField(blank=True)),
                ('b8_3', models.TextField(blank=True)),
                ('b8_4', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
                ('poyasitelniyform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerobjectpoyasitelniyformtable1', to='topografiya.poyasitelniyform')),
            ],
            options={
                'verbose_name_plural': 'PoyasitelniyFormTable1',
            },
        ),
    ]
