# Generated by Django 4.0.1 on 2022-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0013_remove_aktkomeralform_status_komeral_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktkomeralform',
            name='a10',
            field=models.TextField(blank=True),
        ),
    ]
