# Generated by Django 4.0.1 on 2022-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0015_aktpolevoyform_a10'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktpolovoytable6',
            name='a6_6',
            field=models.TextField(blank=True),
        ),
    ]
