# Generated by Django 4.0.1 on 2022-02-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0016_aktpolovoytable6_a6_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolevoyWorkReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='topografiya/static/files/polevoy_rejects', verbose_name='Qaytarilgan fayl')),
                ('reason', models.TextField(blank=True)),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
                ('programowork', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='polevoymworkreject', to='topografiya.workerobject')),
            ],
            options={
                'verbose_name_plural': 'PolevoyWorkReject',
            },
        ),
    ]
