# Generated by Django 4.0.1 on 2022-02-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0019_alter_aktkomeralform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aktkomeralform',
            options={'verbose_name_plural': 'AktKomeralForm'},
        ),
    ]
