# Generated by Django 4.0.1 on 2022-02-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0026_reportreject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkform',
            name='a7',
        ),
        migrations.CreateModel(
            name='ProgramWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 1')),
                ('file2', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 2')),
                ('file3', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 3')),
                ('file4', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 4')),
                ('file5', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 5')),
                ('file6', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 6')),
                ('file7', models.FileField(blank=True, upload_to='topografiya/static/files/programfiles', verbose_name='Fayli 7')),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
                ('programworkform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programworkfiles', to='topografiya.programworkform')),
            ],
            options={
                'verbose_name_plural': 'ProgramWorkFiles',
            },
        ),
    ]
