# Generated by Django 4.0.1 on 2022-02-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0027_remove_programworkform_a7_programworkfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programworkfiles',
            name='file1',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 1'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file2',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 2'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file3',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 3'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file4',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 4'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file5',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 5'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file6',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 6'),
        ),
        migrations.AlterField(
            model_name='programworkfiles',
            name='file7',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/programfiles/files', verbose_name='Fayli 7'),
        ),
    ]
