# Generated by Django 4.0.1 on 2022-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0031_alter_programworkfiles_programworkform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktpolevoyform',
            name='a104',
        ),
    ]
