# Generated by Django 4.0.1 on 2022-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0033_aktpolevoyform_a104'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktpolovoytable7',
            name='a7_6',
            field=models.TextField(blank=True),
        ),
    ]
