# Generated by Django 4.0.1 on 2022-02-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0034_aktpolovoytable7_a7_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktpolovoytable8',
            name='a8_5',
        ),
    ]
