# Generated by Django 4.0.1 on 2022-02-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0035_remove_aktpolovoytable8_a8_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktpolovoytable2',
            name='a2_7',
        ),
    ]
