# Generated by Django 4.0.1 on 2022-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0037_remove_aktpolevoyform_a100_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktpolevoyform',
            name='a71',
            field=models.TextField(blank=True),
        ),
    ]
