# Generated by Django 4.0.1 on 2022-02-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0038_aktpolevoyform_a71'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktkomeralform',
            name='a63',
        ),
        migrations.RemoveField(
            model_name='aktkomeralform',
            name='a64',
        ),
    ]
