# Generated by Django 4.0.1 on 2022-03-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0042_poyasitelniyform_b_3_alter_lines_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkform',
            name='a7',
            field=models.TextField(blank=True),
        ),
    ]
