# Generated by Django 4.0.1 on 2022-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0043_programworkform_a7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkform',
            name='a7',
        ),
    ]
