# Generated by Django 4.0.1 on 2022-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0044_remove_programworkform_a7'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkform',
            name='a7',
            field=models.TextField(blank=True),
        ),
    ]
