# Generated by Django 4.0.1 on 2022-03-05 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0045_programworkform_a7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdowork',
            name='branch',
        ),
    ]
