# Generated by Django 4.0.1 on 2022-03-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0046_remove_pdowork_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.TextField(blank=True),
        ),
    ]
