# Generated by Django 4.0.1 on 2022-03-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0047_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerobject',
            name='topo_plan',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/topoplans', verbose_name='Topo plan fayli'),
        ),
    ]
