# Generated by Django 4.0.1 on 2022-03-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0048_workerobject_topo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktkomeralform',
            name='file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/akt-kameral', verbose_name='AKT file'),
        ),
    ]
