# Generated by Django 4.0.1 on 2022-03-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0049_aktkomeralform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktpolevoyform',
            name='file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/akt-polevoy', verbose_name='AKT polevoy file'),
        ),
    ]
