# Generated by Django 4.0.1 on 2022-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0051_aktpolevoyform_a72'),
    ]

    operations = [
        migrations.AddField(
            model_name='polevoyworkreject',
            name='aktfile',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/polevoy_rejects', verbose_name='Qaytarilgan aktfile'),
        ),
    ]
