# Generated by Django 4.0.1 on 2022-03-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0053_remove_polevoyworkreject_aktfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktpolevoyform',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
