# Generated by Django 4.0.1 on 2022-03-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0054_aktpolevoyform_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='polevoyworkreject',
            name='rejected_file',
            field=models.FileField(blank=True, upload_to='topografiya/static/files/polevoy_rejects', verbose_name='Qaytarilgan fayl'),
        ),
        migrations.AddField(
            model_name='polevoyworkreject',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
