# Generated by Django 4.0.1 on 2022-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0055_polevoyworkreject_rejected_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polevoyworkreject',
            name='rejected_file',
            field=models.TextField(blank=True),
        ),
    ]
