# Generated by Django 4.0.1 on 2022-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0056_alter_polevoyworkreject_rejected_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktkomeralform',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kameralworkreject',
            name='rejected_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kameralworkreject',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
