# Generated by Django 4.0.1 on 2022-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0057_aktkomeralform_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderkomeralworkreject',
            name='rejected_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaderkomeralworkreject',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
