# Generated by Django 4.0.1 on 2022-03-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0059_workerobject_status_printer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkformtable2',
            name='a9_2_7',
        ),
    ]
