# Generated by Django 4.0.1 on 2022-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0060_remove_programworkformtable2_a9_2_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='programworkform',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
