# Generated by Django 4.0.1 on 2022-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0061_programworkform_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='programwork',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programworkreject',
            name='rejected_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programworkreject',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
