# Generated by Django 4.0.1 on 2022-03-16 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0062_programwork_version_programworkreject_rejected_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktpolovoytable7',
            name='a7_6',
        ),
    ]
