# Generated by Django 4.0.1 on 2022-03-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0063_remove_aktpolovoytable7_a7_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programworkfiles',
            name='file1',
        ),
    ]
