# Generated by Django 4.0.1 on 2022-03-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0064_remove_programworkfiles_file1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='worker_geodezis',
        ),
        migrations.RemoveField(
            model_name='object',
            name='worker_ispolnitel',
        ),
        migrations.RemoveField(
            model_name='object',
            name='worker_leader',
        ),
        migrations.RemoveField(
            model_name='object',
            name='worker_ogogd',
        ),
        migrations.AddField(
            model_name='object',
            name='worker',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='topografiya.worker'),
            preserve_default=False,
        ),
    ]
