# Generated by Django 4.0.1 on 2022-03-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0065_remove_object_worker_geodezis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdowork',
            name='status_start',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
