# Generated by Django 4.0.1 on 2022-03-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0066_pdowork_status_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='worker_geodezis',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_geodezis', to='topografiya.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='worker_leader',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workerleader', to='topografiya.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='worker_printer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_printer', to='topografiya.worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='worker_reporter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_reporter', to='topografiya.worker'),
            preserve_default=False,
        ),
    ]
