# Generated by Django 4.0.1 on 2022-03-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0067_object_worker_geodezis_object_worker_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='worker',
        ),
        migrations.AddField(
            model_name='object',
            name='worker_ispolnitel',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workerispolnitel', to='topografiya.worker'),
            preserve_default=False,
        ),
    ]
