# Generated by Django 4.0.1 on 2022-03-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0068_remove_object_worker_object_worker_ispolnitel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderworkerleader', to='topografiya.worker'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_receiver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderworkerispolnitel', to='topografiya.worker'),
        ),
    ]
