# Generated by Django 4.0.1 on 2022-03-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0069_alter_order_order_creator_alter_order_order_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_id',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userhistory', to='topografiya.worker'),
            preserve_default=False,
        ),
    ]
