# Generated by Django 4.0.1 on 2022-03-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0070_remove_history_user_id_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='worker_geodezis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_geodezis', to='topografiya.worker'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_ispolnitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerispolnitel', to='topografiya.worker'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerleader', to='topografiya.worker'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_printer', to='topografiya.worker'),
        ),
        migrations.AlterField(
            model_name='object',
            name='worker_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_reporter', to='topografiya.worker'),
        ),
    ]
