# Generated by Django 4.0.1 on 2022-03-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0072_alter_order_order_creator_alter_order_order_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user_id',
        ),
    ]
