# Generated by Django 4.0.1 on 2022-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0073_rename_user_history_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerobject',
            name='active_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
