# Generated by Django 4.0.1 on 2022-03-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0075_aktkomeralform_active_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktkomeralform',
            name='status_save',
            field=models.IntegerField(default=0),
        ),
    ]
