# Generated by Django 4.0.1 on 2022-03-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0076_aktkomeralform_status_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('active_time', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status_new', models.IntegerField(default=0)),
                ('status_sended', models.IntegerField(default=0)),
                ('status_recived', models.IntegerField(default=0)),
                ('status_deleted', models.IntegerField(default=0)),
                ('message_reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagereciver', to='topografiya.worker')),
                ('message_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagesender', to='topografiya.worker')),
            ],
            options={
                'verbose_name_plural': 'Xabarlar',
            },
        ),
    ]
