# Generated by Django 4.0.1 on 2022-04-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0077_xabarlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programworkform',
            name='program_work_creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='programwork', to='topografiya.worker'),
        ),
    ]
