# Generated by Django 4.0.1 on 2022-04-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0079_report_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportreject',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
