# Generated by Django 4.0.1 on 2022-04-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0080_reportreject_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
