# Generated by Django 4.0.1 on 2022-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0081_branch_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('amount', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Periods',
            },
        ),
    ]
