# Generated by Django 4.0.1 on 2022-04-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0082_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('code', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'WorkTypes',
            },
        ),
    ]
