# Generated by Django 4.0.1 on 2022-04-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0085_delete_branch1_alter_pdowork_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdowork',
            name='department',
        ),
        migrations.AlterField(
            model_name='pdowork',
            name='work_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workperiod', to='topografiya.period'),
        ),
        migrations.AlterField(
            model_name='pdowork',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktype', to='topografiya.worktype'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workerbranch', to='topografiya.branch'),
        ),
        migrations.CreateModel(
            name='SubDivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='topografiya.department')),
            ],
            options={
                'verbose_name_plural': 'SubDivisions',
            },
        ),
        migrations.AddField(
            model_name='pdowork',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksubdivision', to='topografiya.subdivisions'),
        ),
    ]
