# Generated by Django 4.0.1 on 2022-04-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0087_remove_worker_department_worker_subdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdowork',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workbranch', to='topografiya.branch'),
        ),
    ]
