# Generated by Django 4.0.1 on 2022-04-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0089_rename_subdivision_pdowork_subdivisiona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdowork',
            old_name='subdivisiona',
            new_name='subdivision',
        ),
    ]
