# Generated by Django 4.0.1 on 2022-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topografiya', '0090_rename_subdivisiona_pdowork_subdivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('0', 'Ishchi'), ('1', "Bo'lim boshlig'i"), ('2', 'Geodezis'), ('3', 'Printer'), ('4', 'Reporter')], default='0', max_length=10, verbose_name='Ishchi'),
        ),
    ]
