"""
Django settings for newproj project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SESSION_COOKIE_AGE = 60 * 60 * 24 * 1    # 1 kun

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!gq#3^5z+-mu+vw^=i!xly%nj%whi&#kj$f&l!+=%3f8eor9d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'topografiya',
    'leaflet',
    'django.contrib.gis',
    'django.contrib.humanize',
    'django_filters',
    'mathfilters',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'newproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'newproj.wsgi.application'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'newproj',
        'USER': 'myuser',
        'PASSWORD': 'mypass',
        'HOST': 'localhost',
        'PORT': '',                      # Set to empty string for default.
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = '/signin'
LOGOUT_REDIRECT_URL = '/signin'
DOCS_ROOT='topografiya/static/files/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LEAFLET_CONFIG={
'DEFAULT_CENTER':(41.41264,63.454122),
'DEFAULT_ZOOM':6,
'MAX_ZOOM':20,
'MIN_ZOOM':1,
# 'SCALE': 'both',

'TILES':[

('OpenStreetMap','http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/ {y}.png',
    {'attribution':'OpenStreetMap'}),

('GoogleStreet','http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),

('GoogleTerrain','http://{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),
('GoogleHybrid','http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),

('GoogleSet','http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    {
               'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleSet'}),




],

'ATTRIBUTION_PREFIX':'',
# 'MINIMAP':True,
# 'RESET_VIEW':False,
#'ATTRIBUTION_PREFIX':"<a href='http://www.uzgashkliti.uz'>Uzgashkliti</a>",


}
